# Generated by Django 6.1 on 2026-08-19 08:02

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(help_text='Month (1-12)')),
                ('year', models.PositiveIntegerField(help_text='Year (e.g. 2026)')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('hra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='House Rent Allowance')),
                ('medical_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('special_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tax_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Tax / TDS')),
                ('provident_fund', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Provident Fund (PF)')),
                ('other_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('gross_salary', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('PROCESSING', 'Processing')], default='UNPAID', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', 'Direct Bank Transfer'), ('CHEQUE', 'Cheque'), ('CASH', 'Cash')], default='BANK_TRANSFER', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='employees.employee')),
            ],
            options={
                'ordering': ['-year', '-month', 'employee__employee_id'],
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
